"""tao bang users va devices

Revision ID: cda85f1da43c
Revises: 
Create Date: 2026-08-21 10:20:08.215529
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cda85f1da43c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('ix_devices_owner_id_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index('ix_devices_status', ['status'], unique=False)
        batch_op.create_index('uq_devices_owner_id_name', ['owner_id', 'name'], unique=True)
        batch_op.create_index('uq_devices_serial', ['serial'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('uq_users_email', ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_users_email')

    op.drop_table('users')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index('uq_devices_serial')
        batch_op.drop_index('uq_devices_owner_id_name')
        batch_op.drop_index('ix_devices_status')
        batch_op.drop_index('ix_devices_owner_id_status')

    op.drop_table('devices')
    # ### end Alembic commands ###
